stages:
  - test

language: bash
sudo: required
dist: xenial

before_script:
  - export DISPLAY=:99.0
  - if [[ "$TRAVIS_OS_NAME" == "linux" && -f "/etc/init.d/xvfb" ]]; then
    sh -e /etc/init.d/xvfb start;
    fi

jobs:
  include:
    - stage: test
      name: "Lint Dockerfiles"
      # Use container-based infrastructure for quicker build start-up
      sudo: false
      # Use generic image to cut start-up time
      language: generic
      env:
        # Path to 'hadolint' binary
        HADOLINT: "${HOME}/hadolint"
      install:
        # Download hadolint binary and set it as executable
        - curl -sL -o ${HADOLINT} "https://github.com/hadolint/hadolint/releases/download/v1.16.0/hadolint-$(uname -s)-$(uname -m)"
          && chmod 700 ${HADOLINT}
      script:
        # List files which name starts with 'Dockerfile'
        # eg. Dockerfile, Dockerfile.build, etc.
        - git ls-files --exclude='Dockerfile*' --ignored | xargs --max-lines=1 ${HADOLINT}

    - stage: test
      name: "Lint markdown"
      language: node_js
      node_js:
        - "11"
      before_install:
        - yarn install
      script:
        - yarn run lint-md
